### ISSUE TITLE
32-bit download link broken

### ISSUE THREAD

**Issue by 3lm4r** [bombergio/choco-mysql-connector-odbc#21]
MySQL download link for 32-bit version is broken. ATM it seems the 32-bit MSI Installer for version 8.1 is not delivered by Oracle.

**Comment by bombergio** [comment]
Thanks for raising the issue! MySQL dropped 32-bit support for the 8.0 in the past [but returned it ](https://dev.mysql.com/blog-archive/32-bit-odbc-driver-8-0-for-windows-is-back/) based on community feedback.
This time, they dropped it again.
I'll update the manifest to exclude the 32-bit version.

**Comment by bombergio** [comment]
I've released a new "fake" version `8.1.0-x64-fix`, as Chocolatey does not allow package version override.
All references to 32-bit binaries are removed and the installation script will exit with an error on the 32-bit system.
